name: build bgi

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest

    env:
      LANG: "zh_CN.UTF-8"
      LC_ALL: "zh_CN.UTF-8"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Chinese font
      run: |
        Invoke-WebRequest -Uri "https://noto-website-2.storage.googleapis.com/pkgs/NotoSansCJKtc-hinted.zip" -OutFile "NotoSansCJKtc.zip"
        Expand-Archive -Path "NotoSansCJKtc.zip" -DestinationPath "$env:windir/Fonts"

    - name: Set console output encoding to UTF-8
      shell: pwsh
      run: |
        $OutputEncoding = [System.Text.Encoding]::UTF8
        [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
        echo "输出测试：你好，中文世界！"
