name: build bgi

on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest

    env:
      LANG: "zh_CN.UTF-8"
      LC_ALL: "zh_CN.UTF-8"

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set PowerShell output encoding to UTF-8
      shell: pwsh
      run: |
        $OutputEncoding = [System.Text.Encoding]::UTF8
        [Console]::OutputEncoding = [System.Text.Encoding]::UTF8
        echo "测试中文输出：你好，世界！"

    - name: Create file with Chinese name
      run: |
        $fileName = "测试文件.txt"
        "这是一个中文文件名称的测试内容。" > $fileName

    - name: Verify file name
      run: |
        dir
